stages:
  - make_assets
  - embed_reveal
  - docusaurus

build_dir: /build
output_type: last
output_dir: /output

make_assets:
  plugin: command
  options:
    command: make
    locations:
      - chapters/web-application-security/web-basics/slides
      - chapters/web-application-security/cookies-and-session-management/slides
      # - chapters/web-application-security/sql-injection/slides
      - chapters/web-application-security/cross-site-scripting/slides
      # - chapters/web-application-security/exotic-attacks/slides
      # - chapters/web-application-security/overview/slides
      # - chapters/system-and-data-security/framework-api-vulnerabilities/slides
      # - chapters/system-and-data-security/privilege-escalation/slides
      # - chapters/system-and-data-security/end-to-end-attack/slides
      # - chapters/system-and-data-security/overview/slides
      - chapters/network-and-communication-security/enumeration-and-recon/slides
      - chapters/network-and-communication-security/securing-communication/slides
      # - chapters/network-and-communication-security/overview/slides
    args:
      - all

embed_reveal:
  plugin: reveal_embed
  options:
    target: docusaurus
    extension: mdx
    build:
      web-basics: web-basics
      cookies-and-session-management: cookies-and-session-management
      securing-communication: securing-communication
      # sql-injection: sql-injection
      enumeration-and-recon: enumeration-and-recon
      cross-site-scripting: cross-site-scripting
      enumeration-and-recon: enumeration-and-recon
      # framework-api-vulnerabilities: framework-api-vulnerabilities
      # exotic-attacks: exotic-attacks
      # privilege-escalation: privilege-escalation
      # end-to-end-attack: end-to-end-attack
      
docusaurus:
  plugin: docusaurus
  options:
    course_name: Web Security
    sidebar: js
    structure:
      - Web Application Security:
          - Overview: chapters/web-application-security/overview/README.md
          - Web basics:
              path: chapters/web-application-security/web-basics/
              extra:
                - media/
              subsections:
                - Reading:
                    path: reading/
                    subsections:
                      - Introduction: README.md
                - Slides: /build/embed_reveal/web-basics
          - Cookies and Session Management:
              path: chapters/web-application-security/cookies-and-session-management/
              extra:
                - media/
              subsections:
                - Reading:
                    path: reading/
                    subsections:
                      - Introduction: README.md
                - Slides: /build/embed_reveal/cookies-and-session-management

    static_assets:
      - web-basics: /build/make_assets/chapters/web-application-security/web-basics/slides/_site
      - cookies-and-session-management: /build/make_assets/chapters/web-application-security/cookies-and-session-management/slides/_site
      # - sql-injection: /build/make_assets/chapters/web-application-security/sql-injection/slides/_site
      - cross-site-scripting: /build/make_assets/chapters/web-application-security/cross-site-scripting/slides/_site
      # - exotic-attacks: /build/make_assets/chapters/web-application-security/exotic-attacks/slides/_site

      # - framework-api-vulnerabilities: /build/make_assets/chapters/system-and-data-security/framework-api-vulnerabilities/slides/_site
      # - privilege-escalation: /build/make_assets/chapters/system-and-data-security/privilege-escalation/slides/_site
      # - end-to-end-attack: /build/make_assets/chapters/system-and-data-security/end-to-end-attack/slides/_site

      - enumeration-and-recon: /build/make_assets/chapters/network-and-communication-security/enumeration-and-recon/slides/_site
      - securing-communication: /build/make_assets/chapters/network-and-communication-security/securing-communication/slides/_site
      
    config_meta:
      title: Web Security
      url: http://localhost/
      baseUrl: /web-security/
      onBrokenLinks: warn
      onBrokenMarkdownLinks: warn
    config_socials:
      OCW: https://security.cs.pub.ro/summer-school/wiki/
      Facebook: https://www.facebook.com/SSSUPB/
    copyright_string: SSS Team
